### ISSUE TITLE
telebot.js

### ISSUE THREAD

**Issue by laurobmb** [silvelo/raspbot#1]
hi
you can help to this problem? :(
After running the command initialization "node telebot.js" appears the following problem.

**Unhandled rejection Error: 409 {"ok":false,"error_code":409,"description":"Conflict: another webhook is active"}
    at /Users/Lauro/ownCloud/raspbot/node_modules/node-telegram-bot-api/src/telegramPolling.js:72:15
    at tryCatcher (/Users/Lauro/ownCloud/raspbot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/Lauro/ownCloud/raspbot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/Lauro/ownCloud/raspbot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/Lauro/ownCloud/raspbot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/Lauro/ownCloud/raspbot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/Lauro/ownCloud/raspbot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](/Users/Lauro/ownCloud/raspbot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:383:17)**

**Comment by silvelo** [comment]
@laurobmb sorry but i can't reproduce the error, but seems like you are trying to run two instances of the same node-telegram-bot-api.

You can try to modify the code, in line 41 on telebot.js, replace this line
`const bot = new TelegramBot(configuration.token, { polling: true })`
for this
`const bot = new TelegramBot(configuration.token, { polling: true , webHook:false})`

If all of this doesnt work, try to ask the same issue in node-telegram-bot-api, because seems the problem is with their API.
